---
title: "Expanded metadata for the core NTL-LTER datasets"
author: "Hilary Dugan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    # css: styles.css
  pdf_document: default
---

<style>
code {
  white-space: nowrap;
}
</style>


<!-- Get Libraries -->
```{r libraries, echo=FALSE, message = FALSE, warning = FALSE}
library(xml2)
library(rvest)
library(stringr)
library(tidyverse)
library(formatR)
library(EDIutils)
```

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 500), tidy = TRUE)
```

---

<!-- Get Links -->
```{r pressure, echo=FALSE}
URL <- "https://lter.limnology.wisc.edu/core-datasets/"
pg <- read_html(URL)
links = as_tibble(html_attr(html_nodes(pg, "a"), "href")) %>%
  filter(str_detect(value, 'knb-lter-ntl'))

```

```{r testlink, results='asis', echo = FALSE, message = FALSE, warning = FALSE}
##### Get info from core datasets
options(width = 500)

for (i in 2:nrow(links)) {
  
  # Get dataset URL
  coreLink = links$value[i]
  
  pg2 <- read_html(coreLink)
  linkend = as_tibble(html_attr(html_elements(pg2, "a"), "href")) %>%
    filter(str_detect(value, '/dataviewer')) |> 
    mutate(value = str_sub(value, 2, -1))
  
  ### Dataset link
  newlink = paste0("https://portal.edirepository.org/nis", linkend$value[1])
  
  infile1 <- tempfile()
  download.file(newlink,infile1,method="curl")
  dt1 <- read_csv(infile1, show_col_types = FALSE)
  
  # # Get metadatalink
  # meta = head(html_attr(html_nodes(pg2, "a")[[32]], "href"))
  # metadatalink = paste0("https://portal.edirepository.org/nis/", meta)
  # pg3 <- read_html(metadatalink)
  # html_text2(html_elements(pg3, "li"))

  # Get package ID to get EML metadata
  pckIDinx = which(startsWith(html_text2(html_nodes(pg2, "li")), 'knb'))[1]
  pckID = strsplit(html_text2(html_nodes(pg2, "li"))[[pckIDinx]], split = ' ')[[1]][1]
  
  meta.xml = read_metadata(packageId = pckID)
  eml_keywords <- xml_text(xml_find_all(meta.xml, './/keyword'))
  
  # Keep core areas 
  keepKeywords = eml_keywords[eml_keywords %in% c('Primary Production', 'primary production',
                                                  'Populations', 'populations',
                                                  'inorganic nutrients', 'Inorganic Matter', 
                                                  'Organic Matter', 'organic matter',
                                                  'Disturbance', 'disturbance')]
  
  ### Get title 
  # cat('## ',html_text2(html_elements(pg2, "li"))[27], '\n\n')
  cat('## ', xml_text(xml_find_all(meta.xml, './/title'))[1], '\n\n')

   # Print Keywords
  cat('**Core Areas**: ',paste(keepKeywords, collapse=", "), '\n\n')
  
  # All Keywords
  cat('**Keywords**: ', paste(eml_keywords, collapse=", "), '\n\n')
  
  # Print URL
  cat('**EDI Archive + Metadata**: ',coreLink, '\n\n')
  # Print .csv download
  cat('**.csv download link**: ',newlink, '\n\n')
  
  # variables in dataset
  varnames = names(dt1)
  cat('**Variables include**: ',paste0(varnames, collapse=", "), '\n\n')
  
  # Dates
  if("sampledate" %in% varnames) {
    firstdate = min(dt1$sampledate, na.rm = T)
    enddate = max(dt1$sampledate, na.rm = T)
    
    cat('**Date Range**: ',as.character(firstdate), ' - ', as.character(enddate), '\n\n')
  }
  if("sample_date" %in% varnames) {
    firstdate = min(dt1$sample_date, na.rm = T)
    enddate = max(dt1$sample_date, na.rm = T)
    
    cat('**Date Range**: ',as.character(firstdate), ' - ', as.character(enddate), '\n\n')
  }
  
  # cycle through lakes 
  if("lakeid" %in% varnames) {
    lakenames = unique(dt1$lakeid)
    
    if("depth" %in% varnames) {
      cat('**Lakes included**: ', '\n\n')
      for (n in lakenames) {
        # print lake name
        cat('**', n,'**', ', ', sep = '')
        
        uselake = dt1 |> filter(lakeid == n)
        usedepths = uselake |> group_by(depth) |> tally() |> filter(n > 50) |> pull(depth)
        
        # Print depths for that lake
        cat('depths include: ',paste0(usedepths, collapse=", "), '\n\n')
      } 
    } else {
      # print lake name
      cat('**Lakes included**: ',paste0(lakenames, collapse=", "), '\n\n')
    }
  }
}


```

## Session Info
```{r session}
R.version
```
